fix(discordEnpoints): fix overflow
koreanbots/core pull request #489
Opened 2022-03-26 07:56 UTC by SaidBySolo

maybe close #488

2022-06-16 13:12 UTC, chul0721 approved these changes

2022-08-25 08:24 UTC, chul0721 requested changes

2022-08-25 08:24 UTC, chul0721 commented on pages/calculator.tsx
> +		<div className='text-2xl font-bold inline-flex items-center'>권한: {Object.keys(value).filter(el => value[el]).map(el => Number(el)).reduce((prev, curr) => BigInt(prev) | BigInt(curr), BigInt(0))}
계산 결과를 String()으로 타이핑 해야될것 같아요.

2022-08-25 12:30 UTC, chul0721 approved these changes

2022-08-26 00:31 UTC, SaidBySolo commented
close #512

2022-08-26 00:32 UTC, merged