deps: change discord.js version to v14
koreanbots/core pull request #503
Opened 2022-07-29 15:26 UTC by skinmaker1345

# Discord.js의 버전 업데이트

## 요구 사항
- **Node.js v16.9(혹은 그 이상)**

## 점검이 필요한 변경 사항
- Discord.js 클라이언트의 인텐트: 32767(2^15-1)
- Builder(EmbedBuilder ...)의 검증기능 사용 여부
- GuildFeature
- 데이터베이스와의 간섭 여부?

2022-07-30 01:28 UTC, wonderlandpark requested changes

2022-07-30 01:28 UTC, wonderlandpark commented on pages/api/v1/bots/servers.ts
> +import {EmbedBuilder} from 'discord.js'
minor style
```suggestion
import { EmbedBuilder } from 'discord.js'
```

2022-07-30 01:28 UTC, wonderlandpark commented on pages/api/v2/bots/[id]/index.ts
> +import {Colors, EmbedBuilder} from 'discord.js'
```suggestion
import { Colors, EmbedBuilder } from 'discord.js'
```

2022-07-30 01:28 UTC, wonderlandpark commented on pages/api/v2/management/bots/submits/[id]/[date]/approve.ts
> +import {Colors, EmbedBuilder} from 'discord.js'
```suggestion
import { Colors, EmbedBuilder } from 'discord.js'
```

2022-07-30 01:28 UTC, wonderlandpark commented on pages/api/v2/management/bots/submits/[id]/[date]/approve.ts
> +		})
```suggestion
		if(req.body.reviewer) embed.addFields({name: '📃 정보', value:`심사자: ${req.body.reviewer}`})
```

2022-07-30 01:28 UTC, wonderlandpark commented on pages/api/v2/management/bots/submits/[id]/[date]/deny.ts
> +import {Colors, EmbedBuilder} from 'discord.js'
```suggestion
import { Colors, EmbedBuilder } from 'discord.js'
```

2022-07-30 01:28 UTC, wonderlandpark commented on utils/DiscordBot.ts
> +	intents: 32767
컨피그에서 커스터마이징 하는게 좋아보여요 approve하시면 `.env.demo.local` 에 추가해주세요!
```suggestion
	intents: Number(process.env.DISCORD_CLIENT_INTENTS) ?? 32767
```

2022-07-30 01:28 UTC, wonderlandpark commented on utils/Query.ts
> +			res[0].status = null;
```suggestion
			res[0].status = null
```

2022-08-18 19:32 UTC, zero734kr commented on package.json
> +		"typescript": "4.6.4"
typescript 버전 픽스는 의도된 것인가요

2022-08-18 19:48 UTC, zero734kr commented on pages/_app.tsx
> +		if (script) script.addEventListener('error', () => {ReactGA.ga('send', 'event', 'adblock', 'adblock_' + (navigator.userAgent.match(/Android|BlackBerry|iPhone|iPad|iPod|Opera Mini|IEMobile|WPDesktop
정규식을 외부 유틸 함수로 빼내면 좋을거 같아요

2022-08-18 19:48 UTC, zero734kr commented on pages/addbot.tsx
> +const Advertisement = dynamic(() => import('@components/Advertisement'))
특별히 dynamic component로 불러오신 이유가 있을까요?

2022-08-18 19:48 UTC, zero734kr commented on pages/api/v1/bots/servers.ts
>  		return ResponseWrapper(res, { code: 200, message: '성공적으로 업데이트 했습니다.', version: 1 })
코드스타일이긴 한데 line break 좀 끊어서 해주면 좋을거 같아요

2022-08-18 19:48 UTC, zero734kr commented on pages/api/v2/bots/[id]/index.ts
> +		else if (result === 5)
숫자 5가 명확하게 무슨 뜻인지 불명확하니까 enum으로 ResultState 정리해서 ``result === ResultState.XXX``하면 의도를 이해하기 더 쉬울거 같아요

2022-08-18 19:48 UTC, zero734kr commented on utils/Query.ts
> +async function submitBot(id: string, data: AddBotSubmit):Promise<1|2|3|4|5|SubmittedBot> {
enum SubmissionStatus?

2022-08-18 22:59 UTC, chul0721 commented on pages/addbot.tsx
> +const Advertisement = dynamic(() => import('@components/Advertisement'))
다른 페이지에서도 Advertisement를 dynamic component로 불러와 그대로 적용하였습니다.
또한 이 부분은 [해당 PR 내용](https://github.com/koreanbots/core/pull/508)과 관련이 있는 것 같아요

2022-08-18 23:00 UTC, chul0721 commented on pages/_app.tsx
> +		if (script) script.addEventListener('error', () => {ReactGA.ga('send', 'event', 'adblock', 'adblock_' + (navigator.userAgent.match(/Android|BlackBerry|iPhone|iPad|iPod|Opera Mini|IEMobile|WPDesktop
이 부분도 (이 내용)[https://github.com/koreanbots/core/pull/508]과 관련이 있는것 같아요
나중에 따로 PR 올리겠습니다

2022-08-18 23:12 UTC, skinmaker1345 commented on package.json
> +		"typescript": "4.6.4"
의도되었습니다. 4.7.x버전 이후로는 기존의 코드와 충돌합니다.

2022-08-19 07:48 UTC, chul0721 approved these changes

2022-08-30 07:26 UTC, wonderlandpark approved these changes

2022-08-30 14:28 UTC, merged