feat: add open review deny log and max denies restriction
koreanbots/core pull request #510
Opened 2022-08-14 14:57 UTC by eunwoo1104

- 공개 심사 거부 로그 채널을 추가합니다. (<#1008376563731013643>)
- 3번 이상 거부된 경우 해당 ID로는 더이상 봇 신청을 할 수 없도록 합니다.

2022-08-14 15:06 UTC, wonderlandpark requested changes

2022-08-14 15:06 UTC, wonderlandpark commented on pages/api/v2/bots/[id]/index.ts
> +				message: '더이상 해당 봇에 대한 심사 요청을 하실 수 없습니다.',
```suggestion
				message: '더 이상 해당 봇에 대한 심사 요청을 하실 수 없습니다.',
```
Typo

2022-08-15 09:52 UTC, chul0721 approved these changes

2022-08-15 11:39 UTC, wonderlandpark requested changes

2022-08-15 11:39 UTC, wonderlandpark commented on utils/Query.ts
> +	if(identicalSubmits.length >= 3) return 5
```suggestion
	const identicalSubmits = await knex('submitted').select(['id']).where({ id: botId, state: 2 }).andWhereNot('reason', 'IN', ['PRIVATE', 'OFFLINE', 'ABSENT_AT_DISCORD'])
	if(identicalSubmits.length >= 3) return 5
```

2022-08-15 11:39 UTC, wonderlandpark commented on utils/Query.ts
> +	const sameID = await knex('submitted').select(['id']).where({ id: botId, state: 0 }).andWhereNot('reason', 'IN', ['PRIVATE', 'OFFLINE', 'ABSENT_AT_DISCORD'])
```suggestion
	const sameID = await knex('submitted').select(['id']).where({ id: botId, state: 0 })
```

실수하신 것 같아요

2022-08-15 11:39 UTC, wonderlandpark commented on utils/DiscordBot.ts
> +export const getOpenBotReviewLogChannel = (): Discord.TextChannel => getReviewGuild().channels.cache.get(openBotReviewLogChannelID) as Discord.TextChannel
```suggestion
export const getOpenBotReviewLogChannel = (): Discord.TextChannel => getMainGuild().channels.cache.get(openBotReviewLogChannelID) as Discord.TextChannel
```
공개 심사 로그 채널은 메인 서버에 위치.

2022-08-15 11:40 UTC, wonderlandpark requested changes

2022-08-15 11:40 UTC, wonderlandpark commented on pages/api/v2/management/bots/submits/[id]/[date]/deny.ts
> +		await getOpenBotReviewLogChannel().send(embed)
```suggestion
		await getOpenBotReviewLogChannel().send(openEmbed)
```

`openEmbed` 전송

2022-08-15 11:44 UTC, wonderlandpark commented on pages/api/v2/bots/[id]/index.ts
> +				errors: ['해당 봇은 심사에서 3번 거부되었습니다. 더 이상의 심사를 요청하실 수 없습니다.'],
워딩 수정 및 이의제기 권리의 안내
```suggestion
				errors: ['해당 봇은 심사에서 3회 이상 거부되었습니다. 더 이상의 심사를 요청하실 수 없습니다.', '이의 제기의 경우 문의해주세요.'],
```
이건 선택적으로 수용하시면 될 것 같아요.

2022-08-15 11:45 UTC, eunwoo1104 commented on pages/api/v2/bots/[id]/index.ts
> +				errors: ['해당 봇은 심사에서 3번 거부되었습니다. 더 이상의 심사를 요청하실 수 없습니다.'],
이걸로 바꾸는게 더 자연스러울 것 같네요.

2022-08-15 12:13 UTC, wonderlandpark approved these changes
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/31924512/184633173-9345432d-aa9e-45e8-a8ca-4d2c3c6f0eb5.png">
정상 작동 확인했습니다 lgtm

2022-08-15 12:22 UTC, merged