feat: support webhook
koreanbots/core pull request #514
Opened 2022-08-30 02:48 UTC by chul0721

2022-08-30 02:48 UTC, chul0721 commented
디스코드 웹훅에 대한 지원은 #503 PR이 머지된 후에 개발할 예정입니다.

2022-10-19 00:49 UTC, SaidBySolo commented
@chul0721 #503 머지됐으니 다시검토 해야할것 같아요 :)

2022-10-19 07:46 UTC, wonderlandpark requested changes

2022-10-19 07:46 UTC, wonderlandpark commented on pages/api/v2/bots/[id]/vote.ts
> +		}
하트 하나마다 웹훅을 전송하는 것은 비효율적인 것 같아요. 계속 유지해도 되지만 사용자 정보를 포함하거나 일정 주기마다 하트 변동을 알려주는 등에 개선이 있으면 좋을 것 같아요.

2022-10-19 07:46 UTC, wonderlandpark commented on utils/Query.ts
> +	return data
```suggestion
	return [res[0].webhook, res[0].webhook_status]
```

2022-10-19 07:46 UTC, wonderlandpark commented on utils/Webhook.ts
> +			if(baseURL.startsWith('discord.com/api/webhooks') || baseURL.startsWith('www.discord.com/api/webhooks')) {
canary ptb 도 고려되어도 좋을 것 같네요

2022-10-19 07:46 UTC, wonderlandpark commented on utils/Webhook.ts
> +					.setAuthor({ name: bot.name, iconURL: bot.avatar, url: `https://koreanbots.dev/bots/${id}` })
vanity url에 대한 고려도 필요합니다
makeBotURL() 함수를 사용하죠

2022-10-19 07:46 UTC, wonderlandpark commented on utils/Webhook.ts
> +					await update.webhookStatus(id, 'bots')
webhook 요청이 한 번 실패한 뒤로 해당 웹훅을 유효하지 않다고 판단하는건 유저 경험에 부정적일 수도 있을 것 같아요. 따라서 차라리 실패횟수를 저장해서 특정 횟수 이상으로 가면 더이상 시도하지 않는건 어떨까요? 성공하면 실패횟수를 초기화하고요.

2022-10-19 07:46 UTC, wonderlandpark commented on utils/Yup.ts
> +		.nullable(),
한디리 서비스에 영향(레이트리밋)을 줄 수 있는 특정 서비스는 막는 것도 좋아보여요 (github etc)

2022-10-19 07:46 UTC, wonderlandpark commented on utils/Query.ts
> +async function getWebhook(id: string, type: 'bots' | 'servers'): Promise<string[]|null> {
만약에 추후 웹훅 서비스의 서버리스트로의 확장도 염두해두신다면 함수나 변수명도 한 번 생각해보셔도 좋을 것 같아요! 바꾸실 필요는 없어요.

2023-04-02 12:42 UTC, kijk2869 approved these changes

2023-04-02 12:44 UTC, eunwoo1104 approved these changes

2023-04-03 03:03 UTC, merged